syms M d p q_l c_l q_h c_h
S = solve([q_h == (M - d*(1 - p)*q_l - c_h)/(2*d*(1 + p)), ...
    q_l == (M - d*p*q_h - c_l)/(2*d*(2 - p))],[q_h, q_l], ...
    'ReturnConditions', true);
X = solve([S.q_h > 0, S.q_l > 0, M - d*p*S.q_h - c_l > 0, ...
    M - d*(1 - p)*S.q_l - c_h > 0], [c_l, c_h], 'ReturnConditions', true);